services:
  web:
    container_name: phase10randomizer
    image: denoland/deno:latest
    pull_policy: always
    working_dir: /app
    volumes:
      - .:/app
    command: run --allow-net --allow-read --allow-write --allow-env --allow-run main.ts
    ports:
      - "6116:8000"
    restart: unless-stopped
    environment:
      - DENO_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phase10randomizer.rule=Host(`phase.chis.dev`)"
      - "traefik.http.routers.phase10randomizer.entrypoints=websecure"
      - "traefik.http.routers.phase10randomizer.tls.certresolver=cloudflare"
